# Site settings
title: unfoldingWord API
email: info@unfoldingWord.org
description: Unrestricted biblical content in every language
keywords: Unrestricted biblical content in every language
baseurl: "" # the subpath of your site, e.g. /blog, must NOT end with a slash (/)
url: "https://api.unfoldingword.org" # the base hostname & protocol for your site
twitter_username: unfoldingWord
github_username:  unfoldingWord

keep_files: [css/fonts, assets/img]

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown


